[package]
name = "labyrinth"
version = "0.1.0"
authors = ["Felix Wittwer <dev@felixwittwer.de>"]
edition = "2018"

[dependencies]
clap = { version = "2.32", optional = true }
ohua_codegen = { git = "https://github.com/ohua-dev/ohua-rust-runtime", optional = true }
ohua_runtime = { git = "https://github.com/ohua-dev/ohua-rust-runtime", optional = true }
# use patched version of rust-stm
stm = { git = "https://github.com/feliix42/rust-stm", branch = "retry-count", optional = true }
time = { version = "0.1", optional = true }
tokio-threadpool = { version = "0.1.15", optional = true }
futures = { version = "0.1", optional = true }

[features]
bench = ["time"]
cli = ["clap"]
ohua = ["ohua_codegen", "ohua_runtime"]
transactional = ["stm"]
future = ["ohua", "futures", "tokio-threadpool"]

[[bin]]
name = "simple_sequential"
path = "src/bin/simple_sequential.rs"
required-features = ["cli", "bench"]

[[bin]]
name = "ohua"
path = "src/bin/ohua.rs"
required-features = ["ohua", "cli", "bench"]

[[bin]]
name = "stm"
path = "src/bin/stm.rs"
required-features = ["transactional", "cli", "bench"]

[[bin]]
name = "ohua_futures"
path = "src/bin/ohua_futures.rs"
required-features = ["ohua", "cli", "bench", "future"]
