extra-features:
- tail-recursion
integration-features:
    arch: SharedMemory
    options:
        data-parallelism: 10
        amorphous: 14
debug:
    log-level: info
    core-stages:
      - stage: "dflang-final"
        dump: yes
        abort-after: no


